import { create } from 'zustand';

const initialTab = 'dashboard';

export const useAccountingStore = create<any>((set, get) => ({
  activeTab: initialTab || 'dashboard',
  setActiveTab: (val) => set({ activeTab: typeof val === 'function' ? val(get().activeTab) : val }),
  activeSidebarItem: initialTab || 'dashboard',
  setActiveSidebarItem: (val) => set({ activeSidebarItem: typeof val === 'function' ? val(get().activeSidebarItem) : val }),
  refreshing: false,
  setRefreshing: (val) => set({ refreshing: typeof val === 'function' ? val(get().refreshing) : val }),
  currency: 'LYD',
  setCurrency: (val) => set({ currency: typeof val === 'function' ? val(get().currency) : val }),
  activeSaving: null,
  setActiveSaving: (val) => set({ activeSaving: typeof val === 'function' ? val(get().activeSaving) : val }),
  simAmount: '5000',
  setSimAmount: (val) => set({ simAmount: typeof val === 'function' ? val(get().simAmount) : val }),
  simCostCenter: 'kindergarten',
  setSimCostCenter: (val) => set({ simCostCenter: typeof val === 'function' ? val(get().simCostCenter) : val }),
  isStrictEnforcement: true,
  setIsStrictEnforcement: (val) => set({ isStrictEnforcement: typeof val === 'function' ? val(get().isStrictEnforcement) : val }),
  accounts: (() => { const local = localStorage.getItem('erp_chart_of_accounts_v2'); return local ? JSON.parse(local) : []; })(),
  setAccounts: (val) => set({ accounts: typeof val === 'function' ? val(get().accounts) : val }),
  suppliers: [
    { id: 'sup_1', name: 'شركة البيان للمطبوعات والكتب', category: 'الكتب والوسائل التعليمية', balance: 3200.00, contact: '0912183921', status: 'نشط' },
    { id: 'sup_2', name: 'الشركة الليبية للخدمات والنظافة', category: 'صيانة ومرافق', balance: 1500.00, contact: '0925562181', status: 'نشط' },
    { id: 'sup_3', name: 'شركة الفاف للشحن والنقل البري', category: 'النقل والوقود للرحلات الحافلية', balance: 2800.00, contact: '0917736192', status: 'تحت التسوية' },
  ],
  setSuppliers: (val) => set({ suppliers: typeof val === 'function' ? val(get().suppliers) : val }),
  journalEntries: (() => { const local = localStorage.getItem('erp_journal_entries_v2'); return local ? JSON.parse(local) : []; })(),
  setJournalEntries: (val) => set({ journalEntries: typeof val === 'function' ? val(get().journalEntries) : val }),
  showAddAccountModal: false,
  setShowAddAccountModal: (val) => set({ showAddAccountModal: typeof val === 'function' ? val(get().showAddAccountModal) : val }),
  newAccount: {
    code: '', name: '', type: 'فرعي' as const, classification: 'أصول' as const, balance: 0
  },
  setNewAccount: (val) => set({ newAccount: typeof val === 'function' ? val(get().newAccount) : val }),
  selectedAccountCode: '1000',
  setSelectedAccountCode: (val) => set({ selectedAccountCode: typeof val === 'function' ? val(get().selectedAccountCode) : val }),
  coaSearchQuery: '',
  setCoaSearchQuery: (val) => set({ coaSearchQuery: typeof val === 'function' ? val(get().coaSearchQuery) : val }),
  coaMode: 'view',
  setCoaMode: (val) => set({ coaMode: typeof val === 'function' ? val(get().coaMode) : val }),
  selectedAccTab: 'info',
  setSelectedAccTab: (val) => set({ selectedAccTab: typeof val === 'function' ? val(get().selectedAccTab) : val }),
  inlineBudgetEdit: false,
  setInlineBudgetEdit: (val) => set({ inlineBudgetEdit: typeof val === 'function' ? val(get().inlineBudgetEdit) : val }),
  inlineBudgetVal: 0,
  setInlineBudgetVal: (val) => set({ inlineBudgetVal: typeof val === 'function' ? val(get().inlineBudgetVal) : val }),
  inlineSplits: { kindergarten: 25, primary: 25, middle: 25, secondary: 25 },
  setInlineSplits: (val) => set({ inlineSplits: typeof val === 'function' ? val(get().inlineSplits) : val }),
  coaWorkspaceMode: 'inspector',
  setCoaWorkspaceMode: (val) => set({ coaWorkspaceMode: typeof val === 'function' ? val(get().coaWorkspaceMode) : val }),
  stressScenario: 'none',
  setStressScenario: (val) => set({ stressScenario: typeof val === 'function' ? val(get().stressScenario) : val }),
  expenseStressFactor: 100,
  setExpenseStressFactor: (val) => set({ expenseStressFactor: typeof val === 'function' ? val(get().expenseStressFactor) : val }),
  revenueStressFactor: 100,
  setRevenueStressFactor: (val) => set({ revenueStressFactor: typeof val === 'function' ? val(get().revenueStressFactor) : val }),
  spreadEditCode: null,
  setSpreadEditCode: (val) => set({ spreadEditCode: typeof val === 'function' ? val(get().spreadEditCode) : val }),
  wizardParentId: '5000',
  setWizardParentId: (val) => set({ wizardParentId: typeof val === 'function' ? val(get().wizardParentId) : val }),
  wizardBaseName: '',
  setWizardBaseName: (val) => set({ wizardBaseName: typeof val === 'function' ? val(get().wizardBaseName) : val }),
  wizardClass: 'مصروفات',
  setWizardClass: (val) => set({ wizardClass: typeof val === 'function' ? val(get().wizardClass) : val }),
  coaScanState: 'idle',
  setCoaScanState: (val) => set({ coaScanState: typeof val === 'function' ? val(get().coaScanState) : val }),
  coaAuditFixCount: 0,
  setCoaAuditFixCount: (val) => set({ coaAuditFixCount: typeof val === 'function' ? val(get().coaAuditFixCount) : val }),
  selectedReport: null,
  setSelectedReport: (val) => set({ selectedReport: typeof val === 'function' ? val(get().selectedReport) : val }),
  drillDownStack: [],
  setDrillDownStack: (val) => set({ drillDownStack: typeof val === 'function' ? val(get().drillDownStack) : val }),
  filterFinancialPeriod: '2026',
  setFilterFinancialPeriod: (val) => set({ filterFinancialPeriod: typeof val === 'function' ? val(get().filterFinancialPeriod) : val }),
  filterFromDate: '2026-01-01',
  setFilterFromDate: (val) => set({ filterFromDate: typeof val === 'function' ? val(get().filterFromDate) : val }),
  filterToDate: '2026-12-31',
  setFilterToDate: (val) => set({ filterToDate: typeof val === 'function' ? val(get().filterToDate) : val }),
  filterFiscalYear: '2026',
  setFilterFiscalYear: (val) => set({ filterFiscalYear: typeof val === 'function' ? val(get().filterFiscalYear) : val }),
  filterAccountingPeriod: 'سنوي',
  setFilterAccountingPeriod: (val) => set({ filterAccountingPeriod: typeof val === 'function' ? val(get().filterAccountingPeriod) : val }),
  filterCostCenter: 'all',
  setFilterCostCenter: (val) => set({ filterCostCenter: typeof val === 'function' ? val(get().filterCostCenter) : val }),
  filterAccount: 'all',
  setFilterAccount: (val) => set({ filterAccount: typeof val === 'function' ? val(get().filterAccount) : val }),
  filterActiveOnly: false,
  setFilterActiveOnly: (val) => set({ filterActiveOnly: typeof val === 'function' ? val(get().filterActiveOnly) : val }),
  filterBalanceOnly: false,
  setFilterBalanceOnly: (val) => set({ filterBalanceOnly: typeof val === 'function' ? val(get().filterBalanceOnly) : val }),
  filterSortBy: 'code',
  setFilterSortBy: (val) => set({ filterSortBy: typeof val === 'function' ? val(get().filterSortBy) : val }),
  trialBalanceLevel: 'all',
  setTrialBalanceLevel: (val) => set({ trialBalanceLevel: typeof val === 'function' ? val(get().trialBalanceLevel) : val }),
  trialBalanceMode: 'nested',
  setTrialBalanceMode: (val) => set({ trialBalanceMode: typeof val === 'function' ? val(get().trialBalanceMode) : val }),
  localRoles: (() => { const saved = localStorage.getItem('erp_roles_list_v1'); return saved ? JSON.parse(saved) : []; })(),
  setLocalRoles: (val) => set({ localRoles: typeof val === 'function' ? val(get().localRoles) : val }),
  localUsers: (() => { const saved = localStorage.getItem('erp_users_list_v1'); return saved ? JSON.parse(saved) : []; })(),
  setLocalUsers: (val) => set({ localUsers: typeof val === 'function' ? val(get().localUsers) : val }),
  localPermissionsAuditLog: (() => { const saved = localStorage.getItem('erp_permissions_audit_log_v1'); return saved ? JSON.parse(saved) : []; })(),
  setLocalPermissionsAuditLog: (val) => set({ localPermissionsAuditLog: typeof val === 'function' ? val(get().localPermissionsAuditLog) : val }),
  closingStep: 'check',
  setClosingStep: (val) => set({ closingStep: typeof val === 'function' ? val(get().closingStep) : val }),
  isCheckingReady: false,
  setIsCheckingReady: (val) => set({ isCheckingReady: typeof val === 'function' ? val(get().isCheckingReady) : val }),
  checkedReady: false,
  setCheckedReady: (val) => set({ checkedReady: typeof val === 'function' ? val(get().checkedReady) : val }),
  closingProgress: 0,
  setClosingProgress: (val) => set({ closingProgress: typeof val === 'function' ? val(get().closingProgress) : val }),
  closingProgressMessage: '',
  setClosingProgressMessage: (val) => set({ closingProgressMessage: typeof val === 'function' ? val(get().closingProgressMessage) : val }),
  closingAuditLog: [],
  setClosingAuditLog: (val) => set({ closingAuditLog: typeof val === 'function' ? val(get().closingAuditLog) : val }),
  isYearClosed: (function() { const func = () => {
    return localStorage.getItem('erp_is_year_2026_closed') === 'true';
  }; return func(); })(),
  setIsYearClosed: (val) => set({ isYearClosed: typeof val === 'function' ? val(get().isYearClosed) : val }),
  closingRefNo: 'CLS-2026-001',
  setClosingRefNo: (val) => set({ closingRefNo: typeof val === 'function' ? val(get().closingRefNo) : val }),
  closingDate: (function() { const func = () => {
    return localStorage.getItem('erp_year_2026_closing_date') || '';
  }; return func(); })(),
  setClosingDate: (val) => set({ closingDate: typeof val === 'function' ? val(get().closingDate) : val }),
  openedYear2027: (function() { const func = () => {
    return localStorage.getItem('erp_is_year_2027_opened') === 'true';
  }; return func(); })(),
  setOpenedYear2027: (val) => set({ openedYear2027: typeof val === 'function' ? val(get().openedYear2027) : val }),
  currentClosingYear: '2026',
  setCurrentClosingYear: (val) => set({ currentClosingYear: typeof val === 'function' ? val(get().currentClosingYear) : val }),
  closingDateInput: '2026-12-31',
  setClosingDateInput: (val) => set({ closingDateInput: typeof val === 'function' ? val(get().closingDateInput) : val }),
  newYearStartDateInput: '2027-01-01',
  setNewYearStartDateInput: (val) => set({ newYearStartDateInput: typeof val === 'function' ? val(get().newYearStartDateInput) : val }),
  newYearEndDateInput: '2027-12-31',
  setNewYearEndDateInput: (val) => set({ newYearEndDateInput: typeof val === 'function' ? val(get().newYearEndDateInput) : val }),
  newYearNumberInput: '2027',
  setNewYearNumberInput: (val) => set({ newYearNumberInput: typeof val === 'function' ? val(get().newYearNumberInput) : val }),
  closingDescriptionInput: 'إقفال السنة المالية 2026 م وتدوير الأرصدة للحسابات الدائمة وتصفير بنود قائمة الدخل',
  setClosingDescriptionInput: (val) => set({ closingDescriptionInput: typeof val === 'function' ? val(get().closingDescriptionInput) : val }),
  showPostClosingTrialBalance: false,
  setShowPostClosingTrialBalance: (val) => set({ showPostClosingTrialBalance: typeof val === 'function' ? val(get().showPostClosingTrialBalance) : val }),
  unapprovedAdjustmentsCount: 1,
  setUnapprovedAdjustmentsCount: (val) => set({ unapprovedAdjustmentsCount: typeof val === 'function' ? val(get().unapprovedAdjustmentsCount) : val }),
  localDrillDownUser: (() => { const saved = localStorage.getItem('erp_users_list_v1'); if (saved) { try { return JSON.parse(saved)[0]; } catch(e){} } return null; })(),
  setLocalDrillDownUser: (val) => set({ localDrillDownUser: typeof val === 'function' ? val(get().localDrillDownUser) : val }),
  drillDownHistory: [
    { level: 'reports', title: 'التقارير المالية' }
  ],
  setDrillDownHistory: (val) => set({ drillDownHistory: typeof val === 'function' ? val(get().drillDownHistory) : val }),
  drillDownJvId: null,
  setDrillDownJvId: (val) => set({ drillDownJvId: typeof val === 'function' ? val(get().drillDownJvId) : val }),
  drillDownDoc: null,
  setDrillDownDoc: (val) => set({ drillDownDoc: typeof val === 'function' ? val(get().drillDownDoc) : val }),
  coaForm: {
    code: '',
    nameAr: '',
    nameEn: '',
    parentAccountId: '',
    type: 'فرعي',
    classification: 'أصول',
    natureType: 'مدين',
    costCenterId: '',
    isActive: true,
    notes: '',
    balance: 0,
    annualBudget: 0,
    dimSplit_kindergarten: 25,
    dimSplit_primary: 25,
    dimSplit_middle: 25,
    dimSplit_secondary: 25,
    lastReconciliationDate: '',
    isReconciled: false,
    reconciliationTargetBalance: 0,
  },
  setCoaForm: (val) => set({ coaForm: typeof val === 'function' ? val(get().coaForm) : val }),
  showCoaImportModal: false,
  setShowCoaImportModal: (val) => set({ showCoaImportModal: typeof val === 'function' ? val(get().showCoaImportModal) : val }),
  coaImportText: '',
  setCoaImportText: (val) => set({ coaImportText: typeof val === 'function' ? val(get().coaImportText) : val }),
  showAddJVModal: false,
  setShowAddJVModal: (val) => set({ showAddJVModal: typeof val === 'function' ? val(get().showAddJVModal) : val }),
  newJV: {
    description: '',
    debitAccount: '1101',
    creditAccount: '4101',
    amount: ''
  },
  setNewJV: (val) => set({ newJV: typeof val === 'function' ? val(get().newJV) : val }),
  isJvFullscreen: false,
  setIsJvFullscreen: (val) => set({ isJvFullscreen: typeof val === 'function' ? val(get().isJvFullscreen) : val }),
  selectedJvId: null,
  setSelectedJvId: (val) => set({ selectedJvId: typeof val === 'function' ? val(get().selectedJvId) : val }),
  jvEditMode: 'view',
  setJvEditMode: (val) => set({ jvEditMode: typeof val === 'function' ? val(get().jvEditMode) : val }),
  activeJvTab: 'simple',
  setActiveJvTab: (val) => set({ activeJvTab: typeof val === 'function' ? val(get().activeJvTab) : val }),
  showJvSearchOverlay: false,
  setShowJvSearchOverlay: (val) => set({ showJvSearchOverlay: typeof val === 'function' ? val(get().showJvSearchOverlay) : val }),
  showJvPrintModal: false,
  setShowJvPrintModal: (val) => set({ showJvPrintModal: typeof val === 'function' ? val(get().showJvPrintModal) : val }),
  selectedJvPrintTemplate: 'standard',
  setSelectedJvPrintTemplate: (val) => set({ selectedJvPrintTemplate: typeof val === 'function' ? val(get().selectedJvPrintTemplate) : val }),
  copiedJvLine: null,
  setCopiedJvLine: (val) => set({ copiedJvLine: typeof val === 'function' ? val(get().copiedJvLine) : val }),
  jvTableSearch: '',
  setJvTableSearch: (val) => set({ jvTableSearch: typeof val === 'function' ? val(get().jvTableSearch) : val }),
  jvFocusedRowIndex: -1,
  setJvFocusedRowIndex: (val) => set({ jvFocusedRowIndex: typeof val === 'function' ? val(get().jvFocusedRowIndex) : val }),
  jvColWidths: {
    num: 60,
    code: 120,
    name: 180,
    desc: 260,
    debit: 110,
    credit: 110,
    costCenter: 120,
    actions: 90
  },
  setJvColWidths: (val) => set({ jvColWidths: typeof val === 'function' ? val(get().jvColWidths) : val }),
  activeJvState: {
    id: '',
    date: new Date().toISOString().split('T')[0],
    description: '',
    type: 'بسيط',
    status: 'مسودة',
    debitTotal: 0,
    creditTotal: 0,
    createdByUser: 'سليمان غازي',
    createdAt: '',
    updatedAt: '',
    lines: [
      { id: 'l-1', accountCode: '1101', accountName: 'صندوق النقدية والخزينة الموحدة', description: '', debit: 0, credit: 0, costCenter: 'primary' },
      { id: 'l-2', accountCode: '4101', accountName: 'إيرادات الرسوم الدراسية الموحدة', description: '', debit: 0, credit: 0, costCenter: 'primary' }
    ],
    attachments: [] as string[]
  },
  setActiveJvState: (val) => set({ activeJvState: typeof val === 'function' ? val(get().activeJvState) : val }),
  jvSearchFilters: {
    id: '',
    dateFrom: '',
    dateTo: '',
    accountCode: '',
    user: 'all',
    type: 'all',
    description: '',
    amount: '',
    status: 'all'
  },
  setJvSearchFilters: (val) => set({ jvSearchFilters: typeof val === 'function' ? val(get().jvSearchFilters) : val }),
  jvAuditTrail: [
    { id: 'A-101', jvId: 'JV-2026-001', action: 'إنشاء قيد ترحيل تلقائي', user: 'سليمان غازي', timestamp: '2026-06-20 10:30', details: 'ترحيل أجور المعلمين لشهر مايو' },
    { id: 'A-102', jvId: 'JV-2026-002', action: 'تغذية الصندوق', user: 'سليمان غازي', timestamp: '2026-06-21 11:15', details: 'ترحيل قيد تغذية الصندوق بقيمة 5000' }
  ],
  setJvAuditTrail: (val) => set({ jvAuditTrail: typeof val === 'function' ? val(get().jvAuditTrail) : val }),
  jvAttachmentsList: [],
  setJvAttachmentsList: (val) => set({ jvAttachmentsList: typeof val === 'function' ? val(get().jvAttachmentsList) : val }),
  jvTableMaximized: false,
  setJvTableMaximized: (val) => set({ jvTableMaximized: typeof val === 'function' ? val(get().jvTableMaximized) : val }),
  receiptVouchers: (() => { const local = localStorage.getItem('erp_receipt_vouchers_v2'); return local ? JSON.parse(local) : []; })(),
  setReceiptVouchers: (val) => set({ receiptVouchers: typeof val === 'function' ? val(get().receiptVouchers) : val }),
  paymentVouchers: (() => { const local = localStorage.getItem('erp_payment_vouchers_v2'); return local ? JSON.parse(local) : []; })(),
  setPaymentVouchers: (val) => set({ paymentVouchers: typeof val === 'function' ? val(get().paymentVouchers) : val }),
  receiptVoucherForm: {
    date: new Date().toISOString().split('T')[0],
    school: 'مدرسة الأسرة الحديثة - فرع طرابلس',
    stage: 'الابتدائي',
    costCenter: 'primary',
    receivedFrom: 'محمد أحمد الفيتوري',
    operationType: 'رسوم دراسية',
    paymentMethod: 'نقدي',
    receivingAccount: '1101', // صندوق الخزينة الرئيسي (كاش)
    amount: '',
    against: 'دفعة من الرسوم الدراسية للعام الجديد',
    attachmentName: '',
    notes: 'تم ترحيل السند وتوطين الأرصدة تلقائياً بنظام القيد المزدوج المعتمد'
  },
  setReceiptVoucherForm: (val) => set({ receiptVoucherForm: typeof val === 'function' ? val(get().receiptVoucherForm) : val }),
  paymentVoucherForm: {
    date: new Date().toISOString().split('T')[0],
    beneficiary: 'شركة البيان للمطبوعات والكتب',
    costCenter: 'primary',
    paidFromAccount: '1101', // صندوق الخزينة الرئيسي (كاش)
    paidToAccount: '5270', // مصروفات إدارية وتشغيلية أخرى
    amount: '',
    against: 'مستخلص سداد دفعة توريد كتب وقرطاسية مدرسية',
    paymentMethod: 'نقدي',
    attachmentName: '',
    notes: 'خصماً من حساب الميزانية العمومية والتشغيلية المعتمدة لفرع طرابلس'
  },
  setPaymentVoucherForm: (val) => set({ paymentVoucherForm: typeof val === 'function' ? val(get().paymentVoucherForm) : val }),
  selectedReceiptVoucher: null,
  setSelectedReceiptVoucher: (val) => set({ selectedReceiptVoucher: typeof val === 'function' ? val(get().selectedReceiptVoucher) : val }),
  showReceiptDetailModal: false,
  setShowReceiptDetailModal: (val) => set({ showReceiptDetailModal: typeof val === 'function' ? val(get().showReceiptDetailModal) : val }),
  selectedPaymentVoucher: null,
  setSelectedPaymentVoucher: (val) => set({ selectedPaymentVoucher: typeof val === 'function' ? val(get().selectedPaymentVoucher) : val }),
  showPaymentDetailModal: false,
  setShowPaymentDetailModal: (val) => set({ showPaymentDetailModal: typeof val === 'function' ? val(get().showPaymentDetailModal) : val }),
  receiptSearch: '',
  setReceiptSearch: (val) => set({ receiptSearch: typeof val === 'function' ? val(get().receiptSearch) : val }),
  receiptCostCenterFilter: 'all',
  setReceiptCostCenterFilter: (val) => set({ receiptCostCenterFilter: typeof val === 'function' ? val(get().receiptCostCenterFilter) : val }),
  paymentSearch: '',
  setPaymentSearch: (val) => set({ paymentSearch: typeof val === 'function' ? val(get().paymentSearch) : val }),
  paymentCostCenterFilter: 'all',
  setPaymentCostCenterFilter: (val) => set({ paymentCostCenterFilter: typeof val === 'function' ? val(get().paymentCostCenterFilter) : val }),
  bankTransferForm: {
    sourceAccount: '1101', // Cash safe
    destinationAccount: '1102', // Bank
    amount: '',
    reference: 'TRF-2026-77821',
    purpose: 'إيداع إيرادات النقدية اليومية المحصلة في المصرف الجاري'
  },
  setBankTransferForm: (val) => set({ bankTransferForm: typeof val === 'function' ? val(get().bankTransferForm) : val }),
  fixedAssets: (() => { const saved = localStorage.getItem('erp_fixed_assets_v2'); return saved ? JSON.parse(saved) : []; })(),
  setFixedAssets: (val) => set({ fixedAssets: typeof val === 'function' ? val(get().fixedAssets) : val }),
  selectedAssetId: 'FA-01',
  setSelectedAssetId: (val) => set({ selectedAssetId: typeof val === 'function' ? val(get().selectedAssetId) : val }),
  assetDetailTab: 'basic',
  setAssetDetailTab: (val) => set({ assetDetailTab: typeof val === 'function' ? val(get().assetDetailTab) : val }),
  isAssetEditing: false,
  setIsAssetEditing: (val) => set({ isAssetEditing: typeof val === 'function' ? val(get().isAssetEditing) : val }),
  isNewAssetMode: false,
  setIsNewAssetMode: (val) => set({ isNewAssetMode: typeof val === 'function' ? val(get().isNewAssetMode) : val }),
  assetSearchQuery: '',
  setAssetSearchQuery: (val) => set({ assetSearchQuery: typeof val === 'function' ? val(get().assetSearchQuery) : val }),
  assetCategoryFilter: 'all',
  setAssetCategoryFilter: (val) => set({ assetCategoryFilter: typeof val === 'function' ? val(get().assetCategoryFilter) : val }),
  assetStatusFilter: 'all',
  setAssetStatusFilter: (val) => set({ assetStatusFilter: typeof val === 'function' ? val(get().assetStatusFilter) : val }),
  assetCostCenterFilter: 'all',
  setAssetCostCenterFilter: (val) => set({ assetCostCenterFilter: typeof val === 'function' ? val(get().assetCostCenterFilter) : val }),
  assetForm: {
    id: '',
    name: '',
    code: '',
    category: 'سيارات وحافلات',
    group: '',
    manufacturer: '',
    model: '',
    serialNo: '',
    barcode: '',
    status: 'نشط / قيد التشغيل',
    costCenter: 'all',
    branch: 'الفرع الرئيسي - طرابلس',
    location: '',
    responsible: '',
    purchaseDate: '2026-06-30',
    supplier: '',
    invoiceNo: '',
    cost: 0,
    capitalExp: 0,
    scrapValue: 0,
    usefulLife: 5,
    depRate: '20%',
    depMethod: 'قسط ثابت',
    depStartDate: '2026-07-01',
    assetAccount: '1300',
    accDepAccount: '1300',
    depExpenseAccount: '5230',
    accDep: 0,
    netValue: 0,
    isDepPaused: false
  },
  setAssetForm: (val) => set({ assetForm: typeof val === 'function' ? val(get().assetForm) : val }),
  maintenanceForm: {
    type: 'دورية' as 'دورية' | 'طارئة',
    cost: '',
    supplier: '',
    date: '2026-06-30',
    nextDate: '2026-12-30',
    statusAfter: 'ممتاز',
    notes: ''
  },
  setMaintenanceForm: (val) => set({ maintenanceForm: typeof val === 'function' ? val(get().maintenanceForm) : val }),
  transferForm: {
    fromDept: '',
    toDept: '',
    fromBranch: 'الفرع الرئيسي - طرابلس',
    toBranch: 'الفرع الرئيسي - طرابلس',
    fromResponsible: '',
    toResponsible: '',
    date: '2026-06-30',
    notes: ''
  },
  setTransferForm: (val) => set({ transferForm: typeof val === 'function' ? val(get().transferForm) : val }),
  saleForm: {
    price: '',
    buyer: '',
    date: '2026-06-30',
    notes: ''
  },
  setSaleForm: (val) => set({ saleForm: typeof val === 'function' ? val(get().saleForm) : val }),
  discardForm: {
    date: '2026-06-30',
    notes: '',
    lossAccount: '5270'
  },
  setDiscardForm: (val) => set({ discardForm: typeof val === 'function' ? val(get().discardForm) : val }),
  activeAssetModal: 'none',
  setActiveAssetModal: (val) => set({ activeAssetModal: typeof val === 'function' ? val(get().activeAssetModal) : val }),
  fixedAssetReportType: 'all_assets',
  setFixedAssetReportType: (val) => set({ fixedAssetReportType: typeof val === 'function' ? val(get().fixedAssetReportType) : val }),
  fixedAssetViewMode: 'management',
  setFixedAssetViewMode: (val) => set({ fixedAssetViewMode: typeof val === 'function' ? val(get().fixedAssetViewMode) : val }),
  budgets: [
    { id: 'B-01', category: 'الرواتب والأجور الأكاديمية والمكافآت', planned: 250000.00, actual: 235000.00, percentage: 94 },
    { id: 'B-02', category: 'الصيانة السنوية وتطوير الفصول والمبنى', planned: 50000.00, actual: 48000.00, percentage: 96 },
    { id: 'B-03', category: 'الأنشطة والرحلات الطلابية الترفيهية', planned: 30000.00, actual: 12000.00, percentage: 40 },
    { id: 'B-04', category: 'القرطاسية وطباعة الكراسات والامتحانات الفورية', planned: 15000.00, actual: 14500.00, percentage: 96.6 }
  ],
  setBudgets: (val) => set({ budgets: typeof val === 'function' ? val(get().budgets) : val }),
  calcExpr: '',
  setCalcExpr: (val) => set({ calcExpr: typeof val === 'function' ? val(get().calcExpr) : val }),
  calcResult: '0',
  setCalcResult: (val) => set({ calcResult: typeof val === 'function' ? val(get().calcResult) : val }),
  fxAmount: '100',
  setFxAmount: (val) => set({ fxAmount: typeof val === 'function' ? val(get().fxAmount) : val }),
  fxFrom: 'SAR',
  setFxFrom: (val) => set({ fxFrom: typeof val === 'function' ? val(get().fxFrom) : val }),
  fxResult: '128.50',
  setFxResult: (val) => set({ fxResult: typeof val === 'function' ? val(get().fxResult) : val }),
}));
