allowBuilds:
  '@google/genai': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  puppeteer: set this to true or false

overrides:
  nanoid: 3.3.18
  uuid: 14.0.1
  body-parser: 1.20.6
  protobufjs: 7.6.5
