import { CurrencyMaster } from '../../types';

export const currencySeed: CurrencyMaster[] = [
  {
    id: 'cur_usd_001',
    isoCode: 'USD',
    currencyCode: 'USD',
    currencyName: 'US Dollar',
    nativeName: 'Dollar',
    currencySymbol: '$',
    decimalPrecision: 2,
    minorUnit: 'cent',
    symbolPosition: 'Left',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'minus',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cur_eur_002',
    isoCode: 'EUR',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    nativeName: 'Euro',
    currencySymbol: '€',
    decimalPrecision: 2,
    minorUnit: 'cent',
    symbolPosition: 'Left',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'minus',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cur_gbp_003',
    isoCode: 'GBP',
    currencyCode: 'GBP',
    currencyName: 'British Pound',
    nativeName: 'Pound',
    currencySymbol: '£',
    decimalPrecision: 2,
    minorUnit: 'penny',
    symbolPosition: 'Left',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'minus',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cur_jpy_004',
    isoCode: 'JPY',
    currencyCode: 'JPY',
    currencyName: 'Japanese Yen',
    nativeName: 'Yen',
    currencySymbol: '¥',
    decimalPrecision: 0,
    minorUnit: 'rin',
    symbolPosition: 'Left',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'minus',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cur_sar_005',
    isoCode: 'SAR',
    currencyCode: 'SAR',
    currencyName: 'Saudi Riyal',
    nativeName: 'ريال سعودي',
    currencySymbol: 'ر.س',
    decimalPrecision: 2,
    minorUnit: 'halala',
    symbolPosition: 'Right',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'minus',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cur_jod_006',
    isoCode: 'JOD',
    currencyCode: 'JOD',
    currencyName: 'Jordanian Dinar',
    nativeName: 'دينار أردني',
    currencySymbol: 'د.أ',
    decimalPrecision: 3,
    minorUnit: 'fils',
    symbolPosition: 'Right',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'brackets',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cur_lyd_007',
    isoCode: 'LYD',
    currencyCode: 'LYD',
    currencyName: 'Libyan Dinar',
    nativeName: 'دينار ليبي',
    currencySymbol: 'د.ل',
    decimalPrecision: 3,
    minorUnit: 'dirham',
    symbolPosition: 'Right',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'minus',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cur_egp_008',
    isoCode: 'EGP',
    currencyCode: 'EGP',
    currencyName: 'Egyptian Pound',
    nativeName: 'جنيه مصري',
    currencySymbol: 'ج.م',
    decimalPrecision: 2,
    minorUnit: 'piastre',
    symbolPosition: 'Right',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'minus',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cur_aed_009',
    isoCode: 'AED',
    currencyCode: 'AED',
    currencyName: 'UAE Dirham',
    nativeName: 'درهم إماراتي',
    currencySymbol: 'د.إ',
    decimalPrecision: 2,
    minorUnit: 'fils',
    symbolPosition: 'Right',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'minus',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cur_kwd_010',
    isoCode: 'KWD',
    currencyCode: 'KWD',
    currencyName: 'Kuwaiti Dinar',
    nativeName: 'دينار كويتي',
    currencySymbol: 'د.ك',
    decimalPrecision: 3,
    minorUnit: 'fils',
    symbolPosition: 'Right',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    negativeNumberFormat: 'minus',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z'
  }
];
