-- Central incident command center for coordinated tenant-school support.
-- Operational records live in the platform control plane and never contain
-- student, payroll, accounting, or other tenant business payloads.

BEGIN;

CREATE TABLE IF NOT EXISTS public.platform_incidents (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    incident_number bigint GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid,
    school_id uuid,
    source text NOT NULL DEFAULT 'central_review',
    source_event_id uuid,
    trace_id text,
    title text NOT NULL,
    description text,
    category text NOT NULL DEFAULT 'application',
    severity text NOT NULL DEFAULT 'sev3',
    impact_scope text NOT NULL DEFAULT 'school',
    status text NOT NULL DEFAULT 'detected',
    owner_auth_user_id uuid,
    owner_name text,
    due_at timestamptz,
    detected_at timestamptz NOT NULL DEFAULT now(),
    acknowledged_at timestamptz,
    resolved_at timestamptz,
    closed_at timestamptz,
    resolution_summary text,
    root_cause text,
    linked_release_id uuid,
    version integer NOT NULL DEFAULT 1,
    created_by_auth_user_id uuid NOT NULL,
    updated_by_auth_user_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_platform_incidents PRIMARY KEY (id),
    CONSTRAINT uq_platform_incidents_number UNIQUE (incident_number),
    CONSTRAINT fk_platform_incidents_tenant FOREIGN KEY (tenant_id)
        REFERENCES public.tenants (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_platform_incidents_school FOREIGN KEY (school_id)
        REFERENCES public.schools (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_platform_incidents_release FOREIGN KEY (linked_release_id)
        REFERENCES public.platform_school_releases (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_platform_incidents_source CHECK (source IN ('automated', 'audit', 'school_report', 'central_review')),
    CONSTRAINT ck_platform_incidents_category CHECK (category IN ('application', 'database', 'access', 'performance', 'subscription', 'integration', 'release', 'security', 'other')),
    CONSTRAINT ck_platform_incidents_severity CHECK (severity IN ('sev1', 'sev2', 'sev3', 'sev4')),
    CONSTRAINT ck_platform_incidents_impact CHECK (impact_scope IN ('school', 'tenant', 'multi_school', 'platform')),
    CONSTRAINT ck_platform_incidents_status CHECK (status IN ('detected', 'triaged', 'assigned', 'in_progress', 'monitoring', 'resolved', 'closed')),
    CONSTRAINT ck_platform_incidents_title CHECK (length(btrim(title)) BETWEEN 4 AND 200),
    CONSTRAINT ck_platform_incidents_description CHECK (description IS NULL OR length(description) <= 5000),
    CONSTRAINT ck_platform_incidents_owner_name CHECK (owner_name IS NULL OR length(btrim(owner_name)) BETWEEN 2 AND 160),
    CONSTRAINT ck_platform_incidents_version CHECK (version >= 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_incidents_source_event
    ON public.platform_incidents (source, source_event_id)
    WHERE source_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_platform_incidents_queue
    ON public.platform_incidents (status, severity, due_at, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_incidents_school
    ON public.platform_incidents (school_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_incidents_owner
    ON public.platform_incidents (owner_auth_user_id, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.platform_incident_events (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    incident_id uuid NOT NULL,
    event_type text NOT NULL,
    from_status text,
    to_status text,
    note text,
    actor_auth_user_id uuid NOT NULL,
    actor_name text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_platform_incident_events PRIMARY KEY (id),
    CONSTRAINT fk_platform_incident_events_incident FOREIGN KEY (incident_id)
        REFERENCES public.platform_incidents (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_platform_incident_events_type CHECK (event_type IN ('created', 'triaged', 'assigned', 'status_changed', 'comment', 'resolved', 'closed', 'reopened', 'release_linked', 'updated')),
    CONSTRAINT ck_platform_incident_events_note CHECK (note IS NULL OR length(note) <= 5000),
    CONSTRAINT ck_platform_incident_events_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_platform_incident_events_timeline
    ON public.platform_incident_events (incident_id, created_at DESC);

ALTER TABLE public.platform_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_incident_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.platform_incidents FROM anon, authenticated;
REVOKE ALL ON TABLE public.platform_incident_events FROM anon, authenticated;

COMMENT ON TABLE public.platform_incidents IS
  'Platform-admin incident queue coordinating detection, assignment, resolution, verification, and closure.';
COMMENT ON TABLE public.platform_incident_events IS
  'Immutable incident timeline; operational notes only and no tenant business payloads.';

NOTIFY pgrst, 'reload schema';
COMMIT;
